
setting_name: CHESS_IR_CG_UT

default_engine: &default_engine 'qwen2.5-coder-32b'

embedding_function: &default_embedd_func "../bge-base"

base_url: &base_url  http://localhost:8001

team_agents:
  information_retriever:
    engine: *default_engine
    tools:
      extract_keywords:
        template_name: 'extract_keywords'
        engine_config:
          engine_name: *default_engine
          temperature: 0.2
          base_url: *base_url
        parser_name: 'python_list_output_parser'
      retrieve_entity: { "embedding_function": *default_embedd_func }
      retrieve_context:
        top_k: 5

  candidate_generator:
    engine: *default_engine
    tools:
      generate_candidate:
        generator_configs:
          - template_name: 'generate_candidate_one'
            engine_config:
              engine_name: *default_engine
              temperature: 0.7
              base_url: *base_url
            parser_name: 'generate_candidate_gemini_markdown_cot'
            sampling_count: 10
          - template_name: 'generate_candidate_two'
            engine_config:
              engine_name: *default_engine
              temperature: 0.7
              base_url: *base_url
            parser_name: 'generate_candidate_gemini_markdown_cot'
            sampling_count: 10

      revise:
        template_name: 'revise_one'
        engine_config:
          engine_name: *default_engine
          temperature: 0.0
          base_url: *base_url
        parser_name: 'revise_new'

#  unit_tester:
#    engine: *default_engine
#    tools:
#      generate_unit_test:
#        template_name: 'generate_unit_tests'
#        engine_config:
#          engine_name: *default_engine
#          temperature: 0.8
#          base_url: *base_url
#        parser_name: 'generate_unit_tests'
#        unit_test_count: 10
#        sampling_count: 1
#
#      evaluate:
#        template_name: 'evaluate'
#        engine_config:
#          engine_name: *default_engine
#          temperature: 0.0
#          base_url: *base_url
#        parser_name: 'evaluate'
