setting_name: CHESS_IR_CG_UT

# 定义 engine_name 的锚点
default_engine: {{default_engine}}
base_url: {{base_url}}

team_agents:
  binary_selector:
    engine: {{default_engine}}
    tools:
      binary_selection:
        template_name: 'binary_selection'
        engine_config:
          engine_name: {{default_engine}}
          temperature: 0.6
          base_url: {{base_url}}
        parser_name: 'binary_selection'
  listwise_selector:
    engine: {{default_engine}}
    tools:
      listwise_selection:
        template_name: 'listwise_selection'
        engine_config:
          engine_name: {{default_engine}}
          temperature: 0.8
          base_url: {{base_url}}
        parser_name: 'listwise_selection'
        sampling_count: 7
  groupwise_selector:
    engine: {{default_engine}}
    tools:
      groupwise_selection:
        template_name: 'groupwise_selection'
        engine_config:
          engine_name: {{default_engine}}
          temperature: 0.6
          base_url: {{base_url}}
        parser_name: 'groupwise_selection'
        sampling_count: 7
  pointwise_selector:
    engine: {{default_engine}}
    tools:
      pointwise_selection:
        template_name: 'pointwise_selection'
        engine_config:
          engine_name: {{default_engine}}
          temperature: 0.2
          base_url: {{base_url}}
        parser_name: 'pointwise_selection'
  unit_tester:
    engine: {{default_engine}}
    tools:
      generate_unit_test:
        template_name: 'generate_unit_tests'
        engine_config:
          engine_name: {{default_engine}}
          temperature: 0.6
          base_url: {{base_url}}
        parser_name: 'generate_unit_tests'
        unit_test_count: 10
        sampling_count: 1

      evaluate:
        template_name: 'evaluate'
        engine_config:
          engine_name: {{default_engine}}
          temperature: 0.2
          base_url: {{base_url}}
        parser_name: 'evaluate'
